# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: reminder
# app and org for use with dashboard.serverless.com
org: yoadw
app: getting-started-7

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  httpApi:
    cors: true
  environment:
    TABLE_NAME:
      Ref: RemindersDynamoDBTable
    PROJECTTYPE: 'slsfw'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:BatchGetItem
      Resource:
        - "Fn::GetAtt": [ RemindersDynamoDBTable, Arn ]
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

# you can add packaging information here
package:
  artifact: target/reminder-latest.jar

functions:
  putItem:
    handler: com.gingos.functions.PutItemHandler
    events:
      - http:
          path: /reminders/{userId}
          method: POST
          request:
            parameters:
              paths:
                userId: true
  getItems:
    handler: com.gingos.functions.GetItemsHandler
    events:
      - http:
          path: /reminders/{userId}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                userId: true
  sendReminderNotification:
    handler: com.gingos.functions.SendReminderNotificationHandler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ RemindersDynamoDBTable, StreamArn ]



# you can add CloudFormation resource templates here
resources:
  Resources:
    RemindersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: reminders-slsfw
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: ReminderId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
          - AttributeName: ReminderId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: TTL
        StreamSpecification:
          StreamViewType: OLD_IMAGE